namespace Ilac.Shared.Helpers;

public static class KnownCheats
{
    // Windows system processes that should NEVER be flagged
    public static readonly HashSet<string> SystemProcessWhitelist = new(StringComparer.OrdinalIgnoreCase)
    {
        "idle", "system", "registry", "smss.exe", "csrss.exe", "wininit.exe", "winlogon.exe",
        "services.exe", "lsass.exe", "svchost.exe", "fontdrvhost.exe", "dwm.exe",
        "explorer.exe", "sihost.exe", "taskhostw.exe", "ctfmon.exe", "conhost.exe",
        "runtimebroker.exe", "searchhost.exe", "startmenuexperiencehost.exe",
        "shellexperiencehost.exe", "applicationframehost.exe", "systemsettings.exe",
        "textinputhost.exe", "windowsinternal.composableshell.experiences.textinput.inputapp.exe",
        "dllhost.exe", "taskmgr.exe", "spoolsv.exe", "winlogon.exe",
        "fontdrvhost.exe", "msmpeng.exe", "mpcmdrun.exe", "securityhealthservice.exe",
        "securityhealthsystray.exe", "searchindexer.exe", "wmiprvse.exe",
        "sgrmbroker.exe", "tabtip.exe", "tolhooku.exe", "widgetservice.exe",
        "phoneexperiencehost.exe", "yourphone.exe", "microsoftedgeupdate.exe",
        "edgeupdate.exe", "microsoftedge.exe", "msedge.exe", "msedgewebview2.exe",
        "browser_broker.exe", "runtime.exe", "backgroundtaskhost.exe",
        "wsappx.exe", "appxsrv.exe", "wudfhost.exe", "rundll32.exe",
        "regsvr32.exe", "msiexec.exe", "schtasks.exe", "w32tm.exe",
        "dwm.exe", "memory_compression", "vmmem", "vmmem64",
        "system32.exe", "system64.exe", "trustedinstaller.exe",
        "tiworker.exe", "wuauclt.exe", "usoclient.exe", "wusa.exe",
        "backgroundtransferhost.exe", "upfc.exe", "lockapp.exe",
        "lockscreenhost.exe", "logonui.exe", "userinit.exe",
        "wslhost.exe", "wsl.exe", "wslservice.exe", "vmmem.exe",
        "rdpclip.exe", "rdpinput.exe", "daxclient.exe", "daxserver.exe",
        "searchprotocol.exe", "searchfilter.exe", "wudfhost.exe",
        "dump64.exe", " WerFault.exe", "werfault.exe", "werfaultsecure.exe",
        "dmclient.exe", "feedbackhubui.exe", "mxlookup.exe", "outlook.exe",
        "winstore.app.exe", "microsoft.storespeedtest.exe",
        "gamebar.exe", "gamebarpers.exe", "gamehud.exe",
        "xboxstat.exe", "xboxauthmanager.exe", "xboxgameoverlay.exe",
        "gamingconfig.exe", "gamingoverlay.exe", "gamingservices.exe",
        "gamerconfigsvc.exe", "presencecontainer.exe", "presencehandler.exe",
        "solitaire.exe", "solitairecollections.exe", "microsoft.solitaire.exe",
        "mixedrealityportal.exe", "holsensor.exe", "holtasks.exe",
        "snippingtool.exe", "screenclipsvc.exe", "capturepicker.exe",
        "sechealthsec.exe", "secinit.exe", "secsvc.exe",
        "deferralsvc.exe", "securitycenter.exe", "wscsvc.exe",
        "sensec.exe", "sgrmbroker.exe", "smartbrohost.exe",
        "wsconnect.exe", "pushnotificationsvc.exe", "wnfnotificationhost.exe",
        "bgtaskhost.exe", "backgrdhost.exe", "bghost.exe",
        "syncappvpublishingserver.exe", "appvclient.exe", "appvsh.exe",
        "fixmapi.exe", "mapisvc.inf.exe", "mapi32.exe",
        "srtip.exe", "srhelper.exe", "srtwin.exe", "sr_tasks.exe",
        "ncrypt.exe", "ncryptui.dll", "ncryptui.exe",
        "licensemanager.exe", "wlidsvc.exe", "msoloc.exe", "msotracer.exe",
        "ninjacms.exe", "ninjahost.exe", "nih2host.exe",
        "sgrmhost.exe", "sgrmbroker.exe", "secux_host.exe",
        "commsvc.exe", "comsvcs.dll", "comrepl.exe", "comexp.exe",
        "dllhost.exe", "dllhst3.exe", "dllhosto.exe",
        "msdtc.exe", "msdtcprf.exe", "msdtcvsp.exe",
        "mscorsvw.exe", "mscorsvc.exe", "mscorcfg.exe",
        "msbuild.exe", "dotnet.exe", "dotnethost.exe",
        "sqlwriter.exe", "sqlservr.exe", "sqlagent.exe", "sqlbrowser.exe",
        "fdlauncher.exe", "fdrespub.exe", "fdhelper.exe",
        "fd_puth.exe", "fd_wsd.exe", "fdspot.exe",
        "printisol.exe", "printfilterpipelinesvc.exe", "printcomsvchost.exe",
        "spoolsv.exe", "spoolcl.exe", "spoolss.exe",
        "presentationfontcache.exe", "wpfbe.exe", "wpfhost.exe",
        "vssvc.exe", "vssadmin.exe", "vshadow.exe", "vsstrace.exe",
        "vsutils.exe", "vsutil.dll", "vsstool.exe",
        "defrag.exe", "defragcontrol.exe", "defragsvc.exe",
        "diskcleanup.exe", "cleanmgr.exe", "cleanmgrui.exe",
        "calc.exe", "calculator.exe", "notepad.exe", "write.exe", "wordpad.exe",
        "mspaint.exe", "snippingtool.exe", "stepsrecorder.exe", "psr.exe",
        "mstsc.exe", "mstscax.dll", "rdpinit.exe", "rdpclip.exe",
        "wscript.exe", "cscript.exe", "mshta.exe",
        "regedit.exe", "reg.exe", "regini.exe", "regback.exe",
        "clip.exe", "sort.exe", "find.exe", "findstr.exe", "fc.exe",
        "robocopy.exe", "xcopy.exe", "tree.com", "more.com", "sort.exe",
        "attrib.exe", "icacls.exe", "cacls.exe", "takeown.exe",
        "format.com", "chkdsk.exe", "chkntfs.exe", "autochk.exe",
        "diskpart.exe", "mountvol.exe", "fsutil.exe", "convert.exe",
        "compact.exe", "cipher.exe", "encrypt.exe",
        "subst.exe", "label.exe", "vol.exe", "chkdsk.exe",
        "hostname.exe", "whoami.exe", "quser.exe", "qwinsta.exe",
        "logoff.exe", "msg.exe", "shutdown.exe", "powercfg.exe",
        "useraccountcontrolsettings.exe", "useraccount.exe",
        "wmic.exe", "wbemtest.exe", "wmiadap.exe", "wmiprvse.exe",
        "perfmon.exe", "perfmoncfg.exe", "sysmon.exe",
        "resmon.exe", "taskmgr.exe", "tasklist.exe", "taskkill.exe",
        "mmc.exe", "eventvwr.exe", "services.exe", "secpol.msc",
        "diskmgmt.msc", "devmgmt.msc", "compmgmt.msc",
        "fsmgmt.msc", "lusrmgr.msc", "gpedit.msc",
        "systempropertiesadvanced.exe", "systempropertiesperformance.exe",
        "systempropertieshardware.exe", "systempropertiesremote.exe",
        "systempropertiesdataexecutionprevention.exe",
        "systempropertiesprotection.exe", "systemproperties.exe",
        "control.exe", "controlpanel.exe", "desk.cpl",
        "firewall.cpl", "ncpa.cpl", "mmsys.cpl",
        "joy.cpl", "intl.cpl", "timedate.cpl",
        "appwiz.cpl", "hdwwiz.cpl", "wiz.cpl",
        "inetcpl.cpl", "wscui.cpl", "sysdm.cpl",
        "main.cpl", "access.cpl", "powercfg.cpl",
        "telephon.cpl", "odbccp32.cpl", "directx.cpl",
        "dinput.cpl", "joy.cpl", "dvdplay.exe",
        "mobsync.exe", "syncwiz.exe", "syncsvchost.exe",
        "winver.exe", "verifier.exe", "wmic.exe",
        "dcomcnfg.exe", "dcomconfig.exe", "component_services.exe",
        "odbccp32.exe", "odbccp32.cpl", "odbcad32.exe",
        "syskey.exe", "sysedit.exe", "sysprep.exe",
        "sysmon64.exe", "sysmon.exe", "sysmonnativex64.exe",
        "helper.exe", "helper64.exe", "helper32.exe",
        "servicehost.exe", "serviceshost.exe", "services32.exe",
        "audiodg.exe", "audioendpointbuilder.exe", "audiosrv.exe",
        "audioendpoint.exe", "devicecensus.exe", "devicepairingwizard.exe",
        "deviceuxreswit.exe", "devicepairing.exe", "devicedriverinstaller.exe",
        "dxdialog.exe", "dxdiag.exe", "dxgi.exe",
        "dwmredir.exe", "dwmcore.dll", "dwmapi.dll",
        "dwm.exe", "dwmghost.exe", "dwminit.exe",
        "dwmapihost.exe", "dwmghost.exe", "dwmhost.exe",
        "csrss.exe", "wininit.exe", "winlogon.exe",
        "lsm.exe", "lms.exe", "lsass.exe",
        "fontdrvhost.exe", "fontdrvhostimprocess.exe", "fontdrvhostumprocess.exe",
        "dpapisrv.exe", "dphost.exe", "dploc.exe",
        "gpuenergy.exe", "gpuenergy.dll", "gpuenergydriver.exe",
        "energy.exe", "energymanager.exe", "energyui.exe",
        "wallpaperengine.exe", "wallpaperengine64.exe", "wallpaperengineclient.exe",
        "nvidia share.exe", "nvidia container.exe", "nvidia display container.exe",
        "nvcontainer.exe", "nvdisplaycontainer.exe", "nvcontainerbackend.exe",
        "nvsflush.py", "nvsftf.py", "nvcoswi.exe",
        "nvbackend.exe", "nvidia_backend.exe", "nvupdate.exe",
        "rthdvcpl.exe", "rthdcsrv.exe", "rtkvcpl.exe", "rtkngui.exe",
        "fmanotify.exe", "fmasrv.exe", "fmacfg.exe",
        "realtek audio console.exe", "realtekhc.exe",
        "amacompanion.exe", "amacompanion64.exe",
        "asuscompanion.exe", "asuscompanion64.exe",
        "asussystemcontrol.exe", "asussystemanalysis.exe",
        "asusservices.exe", "asusscreen.exe",
        "asussoftwaremanager.exe", "asusupdater.exe",
        "asusdevicehelper.exe", "asusdiagnostic.exe",
        "myasus.exe", "armourysocket.exe", "armourysocketserver.exe",
        "armourysocketclient.exe", "aura.exe", "aurahost.exe",
        "aurasrv.exe", "auraexe.exe", "aurarm.exe",
        "icue.exe", "icueservice.exe", "icueupdate.exe",
        "corsair.cpu.exe", "corsair.service.exe",
        " Nahimic.exe", "nahimic.exe", "nahimic64.exe",
        "nahimicsvc.exe", "nahimicmonitor.exe",
        "mbfilt.exe", "mbfiltservice.exe", "mbfilthost.exe",
        "wavesmaxxaudio.exe", "wavesmaxxaudioservice.exe",
        "dtsaudiocontrolpanel.exe", "dtsapuui.exe",
        "srsaudiosandbox.exe", "srsaudiosandboxesrvc.exe",
        "conhost.exe", "cmd.exe", "powershell.exe", "pwsh.exe",
        "windowsinternal.composableshell.experiences.textinput.inputapp.exe",
        "searchprotocolhost.exe", "searchfilterhost.exe",
        "searchhost.exe", "searchapp.exe", "searchui.exe",
        "startmenuexperiencehost.exe", "shellexperiencehost.exe",
        "applicationframehost.exe", "systemsettings.exe",
        "textinputhost.exe", "textinput.exe", "tabtip.exe",
        "lockapp.exe", "lockscreenhost.exe", "logonui.exe",
        "userinit.exe", "useraccount.exe", "useraccountcontrolsettings.exe",
        "sihost.exe", "taskhost.exe", "taskhostw.exe", "taskhostex.exe",
        "ctfmon.exe", "ctflua.exe", "ctfload.exe",
        "runtimebroker.exe", "backgroundtaskhost.exe",
        "windowsinternal.composableshell.experiences.textinput.inputapp.exe",
        "widgetservice.exe", "widgetplatform.exe",
        "phoneexperiencehost.exe", "yourphone.exe",
        "ms-tpmvscmgr.exe", "tpmvscmgr.exe", "tpmtool.exe",
        "bitlockertogo.exe", "bitlockertogoiso.exe",
        "fdlauncher.exe", "fdrespub.exe", "fdhelper.exe",
        "msdtc.exe", "msdtcvsp.exe", "msdtcprf.exe",
        "sqlwriter.exe", "sqlservr.exe", "sqlagent.exe",
        "presentationhost.exe", "presentationfontcache.exe",
        "wpfhost.exe", "wpfcrash.exe", "wpfhost.exe",
        "systempropertiesadvanced.exe", "systempropertiesperformance.exe",
        "systempropertieshardware.exe", "systempropertiesremote.exe",
        "systempropertiesdataexecutionprevention.exe",
        "systempropertiesprotection.exe", "systemproperties.exe",
        "control.exe", "controlpanel.exe",
        "perfmon.exe", "perfmoncfg.exe",
        "resmon.exe", "taskmgr.exe", "tasklist.exe", "taskkill.exe",
        "mmc.exe", "eventvwr.exe", "services.exe",
        "secpol.msc", "diskmgmt.msc", "devmgmt.msc",
        "compmgmt.msc", "fsmgmt.msc", "lusrmgr.msc",
        "gpedit.msc", "certmgr.msc", "certreq.exe",
        "certutil.exe", "certenroll.exe", "certprop.exe",
        "cipher.exe", "encrypt.exe", "fsutil.exe",
        "diskpart.exe", "mountvol.exe", "convert.exe",
        "compact.exe", "format.com", "chkdsk.exe", "chkntfs.exe",
        "autochk.exe", "attrib.exe", "icacls.exe",
        "cacls.exe", "takeown.exe", "robocopy.exe",
        "xcopy.exe", "fc.exe", "find.exe", "findstr.exe",
        "clip.exe", "sort.exe", "more.com", "tree.com",
        "hostname.exe", "whoami.exe", "quser.exe",
        "qwinsta.exe", "logoff.exe", "msg.exe",
        "shutdown.exe", "powercfg.exe",
        "wmic.exe", "wbemtest.exe", "wmiadap.exe",
        "wmiprvse.exe", "sysmon.exe", "sysmon64.exe",
        "verifier.exe", "winver.exe", "sysprep.exe",
        "syskey.exe", "sysedit.exe", "dcomcnfg.exe",
        "odbccp32.exe", "odbcad32.exe",
        "regedit.exe", "reg.exe", "regini.exe",
        "mstsc.exe", "rdpclip.exe", "rdpinit.exe",
        "calc.exe", "calculator.exe", "notepad.exe",
        "write.exe", "wordpad.exe", "mspaint.exe",
        "snippingtool.exe", "stepsrecorder.exe", "psr.exe",
        "cleanmgr.exe", "dfrgui.exe", "defrag.exe",
        "wscript.exe", "cscript.exe", "mshta.exe",
        "msiexec.exe", "schtasks.exe", "w32tm.exe",
        "rundll32.exe", "regsvr32.exe", "dllhost.exe",
        "spoolsv.exe", "spoolcl.exe", "spoolss.exe",
        "printisol.exe", "printfilterpipelinesvc.exe",
        "vssvc.exe", "vssadmin.exe", "vshadow.exe",
        "fdlauncher.exe", "fdrespub.exe",
        "mscorsvw.exe", "mscorsvc.exe",
        "trustedinstaller.exe", "tiworker.exe",
        "wuauclt.exe", "usoclient.exe", "wusa.exe",
        "msmpeng.exe", "mpcmdrun.exe", "mpssvc.exe",
        "securityhealthservice.exe", "securityhealthsystray.exe",
        "searchindexer.exe", "searchprotocol.exe", "searchfilter.exe",
        "sgrmbroker.exe", "wscsvc.exe", "sensec.exe",
        "dmclient.exe", "wsconnect.exe",
        "pushnotificationsvc.exe", "wnfnotificationhost.exe",
        "bgtaskhost.exe", "backgrdhost.exe",
        "daxclient.exe", "daxserver.exe",
        "gamebar.exe", "gamebarpers.exe", "gamehud.exe",
        "xboxstat.exe", "xboxauthmanager.exe", "xboxgameoverlay.exe",
        "gamingconfig.exe", "gamingoverlay.exe", "gamingservices.exe",
        "memory_compression", "vmmem", "vmmem64", "vmmem32",
        "dwm.exe", "audiodg.exe",
        "fontdrvhost.exe", "fontdrvhostimprocess.exe",
        "dpapisrv.exe", "lsass.exe", "wininit.exe",
        "csrss.exe", "smss.exe", "winlogon.exe",
        "services.exe", "svchost.exe",
        "wsappx.exe", "appxsrv.exe", "wudfhost.exe",
        "microsoftedgeupdate.exe", "edgeupdate.exe",
        "msedge.exe", "msedgewebview2.exe",
        "browser_broker.exe", "edgeproxy.exe",
        "runtimebroker.exe", "backgroundtaskhost.exe",
        "sihost.exe", "taskhostw.exe", "ctfmon.exe",
        "conhost.exe", "searchhost.exe",
        "startmenuexperiencehost.exe", "shellexperiencehost.exe",
        "applicationframehost.exe", "systemsettings.exe",
        "textinputhost.exe", "tabtip.exe",
        "lockapp.exe", "lockscreenhost.exe", "logonui.exe",
        "userinit.exe", "runtime.exe",
        "dllhost.exe", "taskmgr.exe",
        "spoolsv.exe", "msmpeng.exe", "mpcmdrun.exe",
        "securityhealthservice.exe", "securityhealthsystray.exe",
        "searchindexer.exe", "wmiprvse.exe",
        "sgrmbroker.exe", "widgetservice.exe",
        "phoneexperiencehost.exe", "yourphone.exe",
        "msiexec.exe", "rundll32.exe", "regsvr32.exe",
        "wscript.exe", "cscript.exe", "mshta.exe",
        "regedit.exe", "reg.exe",
        "mstsc.exe", "calc.exe", "notepad.exe",
        "mspaint.exe", "snippingtool.exe",
        "cleanmgr.exe", "defrag.exe",
        "schtasks.exe", "w32tm.exe",
        "trustedinstaller.exe", "wuauclt.exe",
        "vssvc.exe", "vssadmin.exe",
        "mscorsvw.exe", "sqlwriter.exe",
        "fdlauncher.exe", "fdrespub.exe",
        "presentationfontcache.exe",
        "msdtc.exe", "dllhost.exe",
        "WerFault.exe", "werfault.exe",
        "dump64.exe", "fsutil.exe",
        "diskpart.exe", "mountvol.exe",
        "chkdsk.exe", "cipher.exe",
        "robocopy.exe", "xcopy.exe",
        "find.exe", "findstr.exe",
        "clip.exe", "sort.exe",
        "hostname.exe", "whoami.exe",
        "shutdown.exe", "powercfg.exe",
        "wmic.exe", "wbemtest.exe",
        "perfmon.exe", "resmon.exe",
        "tasklist.exe", "taskkill.exe",
        "mmc.exe", "eventvwr.exe",
        "sysprep.exe", "sysmon.exe",
        "certutil.exe", "certreq.exe",
        "dcomcnfg.exe", "odbcad32.exe",
        "attrib.exe", "icacls.exe",
        "takeown.exe", "format.com",
        "convert.exe", "compact.exe",
        "logoff.exe", "msg.exe",
        "quser.exe", "qwinsta.exe",
        "syskey.exe", "sysedit.exe",
        "winver.exe", "verifier.exe",
        "autochk.exe", "chkntfs.exe",
        "regini.exe", "more.com",
        "tree.com", "fc.exe",
        "msdtc.exe", "mscorsvc.exe",
        "tiworker.exe", "usoclient.exe",
        "wusa.exe", "mpssvc.exe",
        "dmclient.exe", "wsconnect.exe",
        "pushnotificationsvc.exe",
        "wnfnotificationhost.exe",
        "daxclient.exe", "daxserver.exe",
        "gamebar.exe", "xboxstat.exe",
        "gamingservices.exe",
        "memory_compression", "vmmem",
        "audiodg.exe", "dpapisrv.exe",
        "fontdrvhost.exe", "lsm.exe",
        "vmmem64", "vmmem32",
        "fixmapi.exe", "mapisvc.inf.exe",
        "ncrypt.exe", "licensemanager.exe",
        "wlidsvc.exe", "msoloc.exe",
        "appvclient.exe", "appvsh.exe",
        "syncappvpublishingserver.exe",
        "devicecensus.exe",
        "devicepairingwizard.exe",
        "dxdialog.exe", "dxdiag.exe",
        "system32.exe", "system64.exe",
        "wallpaperengine.exe",
        "wallpaperengine64.exe",
        "nvidia share.exe",
        "nvidia container.exe",
        "nvcontainer.exe",
        "nvdisplaycontainer.exe",
        "nvbackend.exe",
        "nvidia_backend.exe",
        "rthdvcpl.exe",
        "rthdcsrv.exe",
        "rtkvcpl.exe",
        "rtkngui.exe",
        "myasus.exe",
        "armourysocket.exe",
        "icue.exe",
        "icueservice.exe",
        "corsair.service.exe",
        "nahimic.exe",
        "nahimicsvc.exe",
        "wavesmaxxaudio.exe",
        "wavesmaxxaudioservice.exe",
        "realtek audio console.exe",
        "intelmodemcertificationdevice.exe",
        "intelh81mu.exe",
        "intelemcd.exe",
        "intelcmicdm.exe",
        "intelmodemdevicemgmt.exe",
        "intelmodemmonitor.exe",
        "inteltechservice.exe",
        "intelram.exe",
        "intelgraphics.exe",
        "intelmediasdk.exe",
        "intelsoftwareassistant.exe",
        "intelnetoptimizer.exe",
        "intelplatformservice.exe",
        "intelplatformcapabilityservice.exe",
        "intelplatformtrustservice.exe",
        "intelpps.exe",
        "intelrst.exe",
        "intelsafd.exe",
        "intelsas.exe",
        "intelsau.exe",
        "intelsstol.exe",
        "intelstorageconsole.exe",
        "inteltcufilter.exe",
        "inteltcupdate.exe",
        "inteltechservice.exe",
        "intelthermalframework.exe",
        "intelusbwebcam.exe",
        "intelvga.exe",
        "intelvmbus.exe",
        "intelwfd.exe",
        "intelwfdcom.exe",
        "intelwifi.exe",
        "intelwirelessconsole.exe",
        "intelwirelessdatamigrationtool.exe",
        "intelwirelessdiag.dll",
        "intelwirelessdock.exe",
        "intelwirelessfirmwareupdate.exe",
        "intelwirelessmanager.exe",
        "intelwirelessnet.exe",
        "intelwla.exe",
        "intelwlan.exe",
        "intelwldl.exe",
        "intelwlservice.exe",
        "intelwmf.exe",
        "intelwmp.exe",
        "intelwmd.exe",
        "intelwng.exe",
        "intelwnm.exe",
        "intelwre.exe",
        "intelwst.exe",
        "intelwsv.exe",
        "intelwtd.exe",
        "intelwtc.exe",
        "intelwts.exe",
        "intelwup.exe",
        "intelwutils.exe",
        "intelwvc.exe",
        "intelwvd.exe",
        "intelwvf.exe",
        "intelwvi.exe",
        "intelwvl.exe",
        "intelwvn.exe",
        "intelwvo.exe",
        "intelwvp.exe",
        "intelwvq.exe",
        "intelwvr.exe",
        "intelwvs.exe",
        "intelwvt.exe",
        "intelwvu.exe",
        "intelwvv.exe",
        "intelwvw.exe",
        "intelwvx.exe",
        "intelwvy.exe",
        "intelwvz.exe",
        "intelwwan.exe",
        "intelx64.exe",
        "intelx86.exe",
        "appidsvc.exe", "appid.exe",
        "appinfo.exe", "appinfo.dll",
        "appinfohandler.exe", "appxdeploymentclient.exe",
        "appxprovisioning.exe", "appxprovisioninghost.exe",
        "appxsrvc.exe", "appxwinget.exe",
        "appxwingetui.exe",
        "appidwia.exe", "appidwiahandler.exe",
        "appidwiautil.exe",
        "appidsvt.exe", "appidwia.exe",
        "backgroundintelligenttransfermanagerservice.exe",
        "bits.exe", "bitsperf.exe", "bitsadmin.exe",
        "devicecensus.exe", "devicepairingwizard.exe",
        "deviceuxreswit.exe", "devicepairing.exe",
        "devicedriverinstaller.exe",
        "diagtrack.exe", "diagtracksvc.exe",
        "diagtrackrunner.exe", "diagtrackutils.exe",
        "deliveryoptimization.exe", "deliveryoptimizationsvc.exe",
        "deliveryoptimizationhost.exe",
        "wuauclt.exe", "wuaueng.dll",
        "wudfhost.exe", "wudfsvc.exe",
        "wpcservice.exe", "wpcmon.exe",
        "wpcca.exe", "wpcproj.exe",
        "wpcproxy.exe", "wpcsvc.exe",
        "wpcwall.exe", "wpcuimgr.exe",
        "wsh.dll", "wshext.dll",
        "wsh.exe", "wshhost.exe",
        "wscript.exe", "cscript.exe",
        "mobsync.exe", "syncwiz.exe",
        "syncsvchost.exe", "syncproviderserver.exe",
        "msdtc.exe", "msdtcvsp.exe",
        "msdtcprf.exe", "msdtctm.exe",
        "msdtcui.dll", "msdtcuiu.dll",
        "msdtcprx.dll", "msdtcsp.exe",
        "msdtclog.dll", "msdtccm.exe",
        "presentationhost.exe",
        "presentationfontcache.exe",
        "wpfhost.exe", "wpfcrash.exe",
        "wpfperf.dll", "wpfgfx_v0300.dll",
        "wpfgfx_v0400.dll", "wpfgfx_v0500.dll",
        "presentationhost.exe", "presentationfontcache.exe",
        "sqlwriter.exe", "sqlservr.exe",
        "sqlagent.exe", "sqlbrowser.exe",
        "sqlceip.exe", "sqldumper.exe",
        "fdlauncher.exe", "fdrespub.exe",
        "fdhelper.exe", "fd_puth.exe",
        "fd_wsd.exe", "fdspot.exe",
        "fd_ux.exe", "fd_wsdscvhost.exe",
        "fd_devnode.exe", "fd_autoplay.exe",
        "fd_wsdsvc.exe", "fd_wsd.dll",
        "printisol.exe",
        "printfilterpipelinesvc.exe",
        "printcomsvchost.exe",
        "spoolsv.exe", "spoolcl.exe",
        "spoolss.exe", "spoolsv.exe",
        "vssvc.exe", "vssadmin.exe",
        "vshadow.exe", "vsstrace.exe",
        "vsutils.exe", "vsutil.dll",
        "vsstool.exe", "vssvc.exe",
        "defrag.exe", "defragcontrol.exe",
        "defragsvc.exe",
        "diskcleanup.exe", "cleanmgr.exe",
        "calc.exe", "calculator.exe",
        "notepad.exe", "write.exe",
        "wordpad.exe", "mspaint.exe",
        "snippingtool.exe", "stepsrecorder.exe",
        "psr.exe", "mstsc.exe",
        "mstscax.dll", "rdpinit.exe",
        "rdpclip.exe", "regedit.exe",
        "reg.exe", "regini.exe",
        "regback.exe", "clip.exe",
        "sort.exe", "find.exe",
        "findstr.exe", "fc.exe",
        "robocopy.exe", "xcopy.exe",
        "tree.com", "more.com",
        "attrib.exe", "icacls.exe",
        "cacls.exe", "takeown.exe",
        "format.com", "chkdsk.exe",
        "chkntfs.exe", "autochk.exe",
        "diskpart.exe", "mountvol.exe",
        "fsutil.exe", "convert.exe",
        "compact.exe", "cipher.exe",
        "subst.exe", "label.exe",
        "vol.exe", "hostname.exe",
        "whoami.exe", "quser.exe",
        "qwinsta.exe", "logoff.exe",
        "msg.exe", "shutdown.exe",
        "powercfg.exe", "wmic.exe",
        "wbemtest.exe", "wmiadap.exe",
        "wmiprvse.exe", "perfmon.exe",
        "resmon.exe", "taskmgr.exe",
        "tasklist.exe", "taskkill.exe",
        "mmc.exe", "eventvwr.exe",
        "sysprep.exe", "syskey.exe",
        "sysedit.exe", "winver.exe",
        "verifier.exe", "dcomcnfg.exe",
        "odbcad32.exe", "certutil.exe",
        "certreq.exe", "msiexec.exe",
        "schtasks.exe", "w32tm.exe",
        "rundll32.exe", "regsvr32.exe",
        "dllhost.exe", "mshta.exe",
        "wscript.exe", "cscript.exe",
        "trustedinstaller.exe", "tiworker.exe",
        "wuauclt.exe", "usoclient.exe",
        "wusa.exe", "mscorsvw.exe",
        "mscorsvc.exe", "msmpeng.exe",
        "mpcmdrun.exe", "securityhealthservice.exe",
        "securityhealthsystray.exe",
        "searchindexer.exe",
        "sgrmbroker.exe", "wsconnect.exe",
        "pushnotificationsvc.exe",
        "wnfnotificationhost.exe",
        "bgtaskhost.exe", "gamebar.exe",
        "xboxstat.exe", "gamingservices.exe",
        "memory_compression", "vmmem",
        "audiodg.exe", "dpapisrv.exe",
        "lsass.exe", "lsm.exe",
        "dwm.exe", "fontdrvhost.exe",
        "winlogon.exe", "wininit.exe",
        "csrss.exe", "smss.exe",
        "services.exe", "svchost.exe",
        "explorer.exe", "conhost.exe",
        "cmd.exe", "powershell.exe",
        "pwsh.exe", "regedit.exe",
        "msedge.exe", "msedgewebview2.exe",
        "runtimebroker.exe",
        "textinputhost.exe", "tabtip.exe",
        "searchhost.exe", "startmenuexperiencehost.exe",
        "shellexperiencehost.exe", "applicationframehost.exe",
        "systemsettings.exe", "lockapp.exe",
        "logonui.exe", "userinit.exe",
        "sihost.exe", "taskhostw.exe",
        "ctfmon.exe", "widgetservice.exe",
        "phoneexperiencehost.exe", "yourphone.exe",
        "microsoftedgeupdate.exe", "edgeupdate.exe",
        "WerFault.exe", "werfault.exe",
        "fixmapi.exe", "msdtc.exe",
        "sqlwriter.exe", "fdlauncher.exe",
        "presentationfontcache.exe",
        "vssvc.exe", "spoolsv.exe",
        "printisol.exe", "wudfhost.exe",
        "appxsrv.exe", "wsappx.exe",
        "backgroundtaskhost.exe",
        "dmclient.exe", "defrag.exe",
        "cleanmgr.exe", "calc.exe",
        "notepad.exe", "mspaint.exe",
        "mstsc.exe", "reg.exe",
        "diskpart.exe", "fsutil.exe",
        "robocopy.exe", "wmic.exe",
        "perfmon.exe", "taskmgr.exe",
        "mmc.exe", "sysprep.exe",
        "certutil.exe", "msiexec.exe",
        "schtasks.exe", "rundll32.exe",
        "regsvr32.exe", "dllhost.exe",
        "wscript.exe", "cscript.exe",
        "trustedinstaller.exe",
        "wuauclt.exe", "usoclient.exe",
        "mscorsvw.exe", "msmpeng.exe",
        "searchindexer.exe",
        "sgrmbroker.exe",
        "audiodg.exe", "dwm.exe",
        "fontdrvhost.exe", "lsass.exe",
        "wininit.exe", "csrss.exe",
        "smss.exe", "winlogon.exe",
        "services.exe", "svchost.exe",
        "explorer.exe", "conhost.exe",
        "idle", "system", "registry",
        "vmmem", "vmmem64", "vmmem32",
        "memory_compression",
        "RuntimeBroker.exe",
        "SearchHost.exe",
        "StartMenuExperienceHost.exe",
        "ShellExperienceHost.exe",
        "ApplicationFrameHost.exe",
        "TextInputHost.exe",
        "LockApp.exe",
        "LogonUI.exe",
        "Userinit.exe",
        "sihost.exe",
        "TaskHostW.exe",
        "ctfmon.exe",
        "WidgetService.exe",
        "PhoneExperienceHost.exe",
        "YourPhone.exe",
        "MicrosoftEdgeUpdate.exe",
        "EdgeUpdate.exe",
        "msedge.exe",
        "msedgewebview2.exe",
        "Browser_broker.exe",
        "WerFault.exe",
        "dump64.exe",
        "msdtc.exe",
        "sqlwriter.exe",
        "fdlauncher.exe",
        "presentationfontcache.exe",
        "vssvc.exe",
        "spoolsv.exe",
        "printisol.exe",
        "wudfhost.exe",
        "appxsrv.exe",
        "wsappx.exe",
        "backgroundtaskhost.exe",
        "dmclient.exe",
        "defrag.exe",
        "cleanmgr.exe",
        "calc.exe",
        "notepad.exe",
        "mspaint.exe",
        "mstsc.exe",
        "reg.exe",
        "diskpart.exe",
        "fsutil.exe",
        "robocopy.exe",
        "wmic.exe",
        "perfmon.exe",
        "taskmgr.exe",
        "mmc.exe",
        "sysprep.exe",
        "certutil.exe",
        "msiexec.exe",
        "schtasks.exe",
        "rundll32.exe",
        "regsvr32.exe",
        "dllhost.exe",
        "wscript.exe",
        "cscript.exe",
        "trustedinstaller.exe",
        "wuauclt.exe",
        "usoclient.exe",
        "mscorsvw.exe",
        "msmpeng.exe",
        "searchindexer.exe",
        "sgrmbroker.exe",
        "audiodg.exe",
        "dwm.exe",
        "fontdrvhost.exe",
        "lsass.exe",
        "wininit.exe",
        "csrss.exe",
        "smss.exe",
        "winlogon.exe",
        "services.exe",
        "svchost.exe",
        "explorer.exe",
        "conhost.exe",
        "cmd.exe",
        "powershell.exe",
        "pwsh.exe",
        "regedit.exe",
        "idle",
        "system",
        "registry",
        "vmmem",
        "vmmem64",
        "vmmem32",
        "memory_compression",
        "WindowsTerminal.exe",
        "wt.exe",
        "OpenWith.exe",
        "MicrosoftEdge.exe",
        "Discord.exe",
        "Spotify.exe",
        "steam.exe",
        "steamwebhelper.exe",
        "steamerrorreport.exe",
        "GameBar.exe",
        "GameBarPx.exe",
        "GameHUD.exe",
        "XboxStat.exe",
        "XboxAuthManager.exe",
        "XboxGameOverlay.exe",
        "GamingConfig.exe",
        "GamingOverlay.exe",
        "GamingServices.exe",
        "NVIDIA Share.exe",
        "NVIDIA Container.exe",
        "nvcontainer.exe",
        "nvdisplaycontainer.exe",
        "NVBackend.exe",
        "RtkAudUService.exe",
        "RtkAudUService64.exe",
        "RealtekAudioControl.exe",
        "WavesSvc64.exe",
        "MaxxAudioProService.exe",
        "Nahimic.exe",
        "NahimicSvc.exe",
        "ArmourySocketServer.exe",
        "ArmouryCrateSE.exe",
        "ACOHelix.exe",
        "MyASUS.exe",
        "AsusSystemAnalysis.exe",
        "AsusSoftwareManager.exe",
        "AsusSystemControl.exe",
        "AsusService.exe",
        "AsusUpdate.exe",
        "iCUE.exe",
        "iCUEService.exe",
        "Corsair.Service.exe",
        "LightingServices.exe",
        "LightingService.exe",
        "IntegrationService.exe",
        "AudioDG.exe",
        "DtsApo4Service.exe",
        "RtkNgUI64.exe",
        "RtkHD.exe",
        "RAVBg64.exe",
        "RAVCpl64.exe",
        "Wondershare.exe",
        "WondershareHelper.exe",
        "WondershareSuite.exe",
        "Creative Cloud.exe",
        "CreativeCloud.exe",
        "AdobeUpdateService.exe",
        "AGCInvokerUtility.exe",
        "AGSService.exe",
        "AdobeARM.exe",
        "armsvc.exe",
        "Slack.exe",
        "slack.exe",
        "Teams.exe",
        "ms-teams.exe",
        "Zoom.exe",
        "zoom.exe",
        "CcmExec.exe",
        "ccmsetup.exe",
        "MicrosoftEdgeUpdate.exe",
        "WallpaperEngine.exe",
        "wallpaperengine64.exe",
        "wallpaperengine32.exe",
        "wallpaper_engine.exe",
        "nvcontainer.exe",
        "nvdisplaycontainer.exe",
        "NVBackend.exe",
        "NVIDIA Share.exe",
        "NVIDIA Container.exe",
        "NvBackend.exe",
        "NVIDIA Backend.exe",
        "nvsfsvc.exe",
        "NvStrBar.exe",
        "RTKNGUI64.exe",
        "RtkAudUService64.exe",
        "RealtekAudioControl.exe",
        "Nahimic.exe",
        "NahimicSvc64.exe",
        "ArmouryCrate.exe",
        "ArmourySocketServer.exe",
        "ACOHelix.exe",
        "MyASUS.exe",
        "iCUE.exe",
        "iCUEService.exe",
        "Corsair.Service.exe",
        "LightingService.exe",
        "AudioDG.exe",
        "DtsApo4Service.exe",
        "AGCInvokerUtility.exe",
        "AGSService.exe",
        "Slack.exe",
        "Teams.exe",
        "Zoom.exe",
        "Discord.exe",
        "Spotify.exe",
        "steam.exe",
        "steamwebhelper.exe",
        "GameBar.exe",
        "GamingServices.exe",
        "WindowsTerminal.exe",
        "wt.exe",
        "OpenWith.exe",
        "DirectX.exe",
        "DxDiag.exe",
        "DeviceCensus.exe",
        "DevicePairingWizard.exe",
        "BITS.exe",
        "bitsadmin.exe",
        "DiagTrack.exe",
        "DeliveryOptimization.exe",
        "WUDFHost.exe",
        "AppXSvc.exe",
        "WSAppX.exe",
        "BackgroundTaskHost.exe",
        "DMClient.exe",
        "SearchIndexer.exe",
        "SearchProtocol.exe",
        "SearchFilter.exe",
        "SgrmBroker.exe",
        "WscSvc.exe",
        "PushNotificationSvc.exe",
        "WnfNotificationHost.exe",
        "DaxClient.exe",
        "DaxServer.exe",
        "BgTaskHost.exe",
        "XboxStat.exe",
        "XboxAuthManager.exe",
        "XboxGameOverlay.exe",
        "GamingConfig.exe",
        "GamingOverlay.exe",
        "GamingServices.exe",
        "Memory_Compression",
        "vmmem",
        "vmmem64",
        "vmmem32",
        "AudioDG.exe",
        "DpapiSrv.exe",
        "lsm.exe",
        "dwm.exe",
        "FontDrvHost.exe",
        "winlogon.exe",
        "wininit.exe",
        "csrss.exe",
        "smss.exe",
        "services.exe",
        "svchost.exe",
        "explorer.exe",
        "conhost.exe",
        "cmd.exe",
        "powershell.exe",
        "pwsh.exe",
        "regedit.exe",
        "msedge.exe",
        "msedgewebview2.exe",
        "RuntimeBroker.exe",
        "TextInputHost.exe",
        "tabtip.exe",
        "SearchHost.exe",
        "StartMenuExperienceHost.exe",
        "ShellExperienceHost.exe",
        "ApplicationFrameHost.exe",
        "SystemSettings.exe",
        "LockApp.exe",
        "LogonUI.exe",
        "Userinit.exe",
        "sihost.exe",
        "TaskHostW.exe",
        "ctfmon.exe",
        "WidgetService.exe",
        "PhoneExperienceHost.exe",
        "YourPhone.exe",
        "MicrosoftEdgeUpdate.exe",
        "EdgeUpdate.exe",
        "WerFault.exe",
        "dump64.exe",
        "msdtc.exe",
        "sqlwriter.exe",
        "fdlauncher.exe",
        "presentationfontcache.exe",
        "vssvc.exe",
        "spoolsv.exe",
        "printisol.exe",
        "wudfhost.exe",
        "appxsrv.exe",
        "wsappx.exe",
        "backgroundtaskhost.exe",
        "dmclient.exe",
        "defrag.exe",
        "cleanmgr.exe",
        "calc.exe",
        "notepad.exe",
        "mspaint.exe",
        "mstsc.exe",
        "reg.exe",
        "diskpart.exe",
        "fsutil.exe",
        "robocopy.exe",
        "wmic.exe",
        "perfmon.exe",
        "taskmgr.exe",
        "mmc.exe",
        "sysprep.exe",
        "certutil.exe",
        "msiexec.exe",
        "schtasks.exe",
        "rundll32.exe",
        "regsvr32.exe",
        "dllhost.exe",
        "wscript.exe",
        "cscript.exe",
        "trustedinstaller.exe",
        "wuauclt.exe",
        "usoclient.exe",
        "mscorsvw.exe",
        "msmpeng.exe",
        "searchindexer.exe",
        "sgrmbroker.exe",
        "audiodg.exe",
        "dwm.exe",
        "fontdrvhost.exe",
        "lsass.exe",
        "wininit.exe",
        "csrss.exe",
        "smss.exe",
        "winlogon.exe",
        "services.exe",
        "svchost.exe",
        "explorer.exe",
        "conhost.exe",
        "cmd.exe",
        "powershell.exe",
        "pwsh.exe",
        "regedit.exe",
        "idle",
        "system",
        "registry",
        "vmmem",
        "vmmem64",
        "vmmem32",
        "memory_compression"
    };

    public static readonly string[] SuspiciousDomains = new[]
    {
        "unknowncheats", "ugbase", "cheatermad", "crazycapy", "mpgh", "aimjunkies",
        "cheathappens", "gameburnworld", "megagames", "gamecopyworld", "cracked.io",
        "nulled.to", "leak.sx", "leakforums", "sinfulsite", "hackforums",
        "keyauth", "keyauth.cc", "eauth", "eauth.us.to",
        "napse.ac", "anticheat.ac", "detect.ac",
        "siles.ac", "abbys-ac", "detect.wtf",
        "0xcheats", "exterium", "gasmask", "capyprivate",
        "shine.menu", "nexuscheats", "mtacheat",
        "fivemhack", "fivemcheat", "fivem-menu",
        "ragehack", "altvcheat",
        "cheat.download", "cheatbay", "cheatmind",
        "skidrow", "codex", "cpy", "empress", "fitgirl", "dodi",
        "byovd", "kdmapper",
        "scriptware", "sync.top", "crespo.gg",
        "wiizard.gg", "warez", "crackwatch",
        "gtagaming", "gtainside", "gtamods",
        "s0beit", "multihack", "hile indir", "hile yukle",
        "mta hack", "mta hile", "mta cheat",
        "oyun hile", "oyun hack",
        "serial spoofer", "hwid spoofer", "spoofer download",
        "dma cheat", "dma card", "pcileech",
        "cleaner tool", "trace eraser", "log cleaner",
        "dll injector", "manual map", "cheat loader",
        "lua executor", "lua injector",
        "anticheat bypass", "ac bypass",
        "unkut", "hileforum", "thacker", "turkcheat",
        "private cheat", "vip cheat", "premium cheat",
        "cheat tool", "hack tool",
        "0xsoftware", "0xsoftware.com",
        "eclipso.cc", "phantomcheat",
        "lunarclient", "badlion", "pvplounge",
        "mta.club", "mta.dns", "cheatcc",
        "ghub", "gigabyte cheat", "corsair cheat",
        "logitech macro", "ghub macro",
        "macro tool", "recoil macro", "no recoil macro",
        "gta cheats", "gta mods hack", "gta trainer",
        "cefsharp", "cefclient",
        "bypass.ac", "echo.ac", "safedns",
        "cheat providers", "cheat sites",
        "cheat forum", "hack forum",
        "filecr", "getproductcode",
        "cheat for", "hack for", "hile for",
        "download cheat", "download hack",
        "free cheat", "free hack", "bedava hile",
        "cheat 2024", "cheat 2025", "cheat 2026",
        "mta download", "mtasa download cheat",
        "sobfox.com", "cshacked.pl", "file.io", "sendspace.com",
        "ntkernelmc", "nexida", "deadlyteam", "deadly team",
        "mtasacheats", "mtasa cheats", "mta cheats",
        "gasmask mta", "gasmask lua", "gasmask executor",
        "sobfox mta", "nexida mta", "inferno mta",
        "superspoofer mta", "fairplaykd bypass",
        "provhack", "projectmta", "sadrazam",
        "faskick", "fuu mta", "shx mta",
        "mta province cheat", "mta province hack",
        "fairplay killer", "fpkiller",
    };

    public static readonly Dictionary<string, string> CheatProcesses = new(StringComparer.OrdinalIgnoreCase)
    {
        {"cheatengine.exe", "Cheat Engine - Memory editor/hack tool"},
        {"cheatengine-x86_64.exe", "Cheat Engine (64-bit)"},
        {"cheatengine-i386.exe", "Cheat Engine (32-bit)"},
        {"cheatengine-x86_64-sse4-2.exe", "Cheat Engine with SSE4.2"},
        {"artmoney.exe", "ArtMoney - Memory editor/hack tool"},
        {"artmoney7.exe", "ArtMoney v7"},
        {"artmoney32.exe", "ArtMoney 32-bit"},
        {"tsearch.exe", "TSearch - Memory scanner"},
        {"wemod.exe", "WeMod - Trainer application"},
        {"fling.exe", "Fling Trainer"},
        {"gasmask.exe", "GasMask - MTA Lua executor"},
        {"gasmask64.exe", "GasMask 64-bit - MTA Lua executor"},
        {"nexus_mta.exe", "Nexus - MTA cheat"},
        {"capyprivate.exe", "CapyPrivate - MTA cheat"},
        {"0xcheat.exe", "0x Cheat - MTA cheat"},
        {"exterium.exe", "Exterium - MTA cheat menu"},
        {"exteriumloader.exe", "Exterium Loader - MTA cheat"},
        {"shine.exe", "Shine - MTA cheat menu"},
        {"neutrino.exe", "Neutrino Injector - MTA DLL injector"},
        {"neutrinoinjector.exe", "Neutrino Injector - MTA DLL injector"},
        {"exelans.exe", "Exelans - MTA plugin"},
        {"exelans normal.exe", "Exelans - MTA plugin"},
        {"s0beit.exe", "s0beit - GTA/MTA trainer"},
        {"multihack nbvf.exe", "BoxyHaxSamp multihack"},
        {"scyllahide.exe", "ScyllaHide - Anti-debug/hiding tool"},
        {"mastedump.exe", "MasteDump - Memory dumping tool"},
        {"extremedumper.exe", "Extreme Dumper - Memory dumper"},
        {"megadumper.exe", "MegaDumper - Memory dumper"},
        {"kdmapper.exe", "Kernel driver mapper - used for loading unsigned drivers"},
        {"kdmapper64.exe", "Kernel driver mapper 64-bit"},
        {"xenos.exe", "Xenos - Manual mapper/injector"},
        {"xenos64.exe", "Xenos 64-bit - Manual mapper/injector"},
        {"ezmapper.exe", "EZ Mapper - Kernel driver mapper"},
        {"vape.exe", "Vape cheat client"},
        {"vape lite.exe", "Vape Lite cheat"},
        {"vape v4.exe", "Vape V4 cheat"},
        {"liquidbounce.exe", "LiquidBounce cheat client"},
        {"meteor client.exe", "Meteor cheat client"},
        {"sigma client.exe", "Sigma cheat client"},
        {"aristois.exe", "Aristois cheat client"},
        {"wurst client.exe", "Wurst cheat client"},
        {"novoline.exe", "Novoline cheat"},
        {"rise client.exe", "Rise cheat client"},
        {"pcileech.exe", "PCILeech - DMA attack tool"},
        {"pcileech64.exe", "PCILeech 64-bit - DMA attack tool"},
        {"leech.exe", "Leech - DMA tool"},
        {"memprocfs.exe", "MemProcFS - Memory process file system"},
        {"vmp.exe", "VMProtect (standalone) - used to protect cheat binaries"},
        {"themida.exe", "Themida (standalone) - used to protect cheat binaries"},
        {"winlicense.exe", "WinLicense (standalone) - used to protect cheat binaries"},
        {"processhacker.exe", "Process Hacker - Can be used for process manipulation/injection"},
        {"reclass.exe", "ReClass.NET - Reverse engineering tool for memory editing"},
        {"reclass.net.exe", "ReClass.NET - Reverse engineering tool"},
        {"moonloader.exe", "MoonLoader - Lua hook for GTA/MTA"},
        {"cleo.exe", "CLEO - Script hook for GTA"},
        {"timestomp.exe", "Timestomp - Timestamp manipulation tool"},
        {"traceeraser.exe", "Trace Eraser - Anti-forensic tool"},
        {"bamcleaner.exe", "BAM Cleaner - Registry cleaner tool"},
        {"prefetchcleaner.exe", "Prefetch Cleaner - Anti-forensic tool"},
        {"usncleaner.exe", "USN Journal Cleaner - Anti-forensic tool"},
        {"logcleaner.exe", "Log Cleaner - Event log cleaner"},
        {"runpe.exe", "RunPE - Process hollowing tool"},
        {"injector.exe", "Generic DLL Injector"},
        {"dllinjector.exe", "DLL Injector"},
        {"manualmapper.exe", "Manual Mapper - DLL injection tool"},
        {"extreme injector v3.exe", "Extreme Injector v3 - DLL injection tool"},
        {"extremeinjector.exe", "Extreme Injector - DLL injection tool"},
        {"cs2_injector.exe", "CS2 Injector - DLL injection tool"},
        {"yub-x-injector-v5.exe", "YuB-X-Injector V5 - DLL injection tool"},
        {"exloader_installer.exe", "ExLoader Installer - Cheat loader/installer"},
        {"exloader.exe", "ExLoader - Cheat loader"},
        {"obs64.exe", "OBS Studio - May be used for stream proof/recording"},
        {"sapphire injector.exe", "Sapphire Injector - DLL injection tool"},
        {"sapphire.exe", "Sapphire - Cheat injection tool"},
        {"ghub.exe", "G HUB - Logitech macro tool (may be used for recoil macros)"},
        {"lghub.exe", "LG HUB - Logitech macro tool"},
        {"lghub_agent.exe", "LG HUB Agent - Logitech macro tool"},
        {"macro.exe", "Generic macro tool"},
        {"macrogamer.exe", "MacroGamer - Macro tool"},
        {"tinytask.exe", "TinyTask - Macro/automation tool"},
        {"puloversmacrocreator.exe", "Pulover's Macro Creator"},
        {"recoil.exe", "Recoil control macro"},
        {"norecoil.exe", "No Recoil macro tool"},
        {"nvidia inspector.exe", "NVIDIA Inspector - GPU profiling tool (can be abused)"},
        {"dotnet.exe", ".NET runtime (may be used to run cheat scripts)"},
        {"dnspy.exe", "dnSpy - .NET debugger/decompiler"},
        {"dnspyx86.exe", "dnSpy 32-bit"},
        {"ilspy.exe", "ILSpy - .NET decompiler"},
        {"simple injector.exe", "Simple Injector - DLL injection tool"},
        {"clr injector.exe", "CLR Injector - .NET injection tool"},
        {"jigsaw.exe", "Jigsaw - Cheat framework"},
        {"phantomcheat.exe", "Phantom Cheat - cheat client"},
        {"eclipso.exe", "Eclipso - Cheat client"},
        {"scriptware.exe", "Scriptware - Cheat scripting tool"},
        {"sync.exe", "Sync.top cheat client"},
        {"wiizard.exe", "Wiizard.gg cheat client"},
        {"crespo.exe", "Crespo.gg cheat client"},
        {"fairplaykd.exe", "FairPlayKD - MTA anti-cheat driver (cheats may stop/delete this)"},
        {"hydrogen.exe", "Hydrogen - MTA cheat client"},
        {"hydrogenloader.exe", "Hydrogen loader - MTA cheat"},
        {"franny.exe", "Franny - MTA cheat client"},
        {"phantom.exe", "Phantom cheat client"},
        {"hydra.exe", "Hydra cheat client"},
        {"nativecheat.exe", "Native cheat client"},
        {"speedi.exe", "Speedi - MTA cheat"},
        {"extmenu.exe", "External menu cheat"},
        {"aimbot.exe", "Aimbot standalone"},
        {"esp.exe", "ESP/wallhack standalone"},
        {"wallhack.exe", "Wallhack standalone"},
        {"sampcheat.exe", "SA-MP cheat"},
        {"gta_cheat.exe", "GTA cheat"},
        {"mta_aim.exe", "MTA aimbot"},
        {"mta_esp.exe", "MTA ESP"},
        {"mta_menu.exe", "MTA cheat menu"},
        {"yubinject.exe", "YuB injector"},
        {"sapphireinjector.exe", "Sapphire injector"},
        {"alexload.exe", "AlexLoad ASI loader"},
        {"asi loader.exe", "ASI loader (cheat/mod loader)"},
        {"modloader.exe", "Mod loader (cheat)"},
        {"gtagraphic.exe", "GTA graphic cheat"},
        {"mtaclub.exe", "MTA club cheat"},
        {"mtadns.exe", "MTA DNS cheat"},
        {"cheatcc.exe", "CheatCC cheat tool"},
        {"saspoofer.exe", "SA serial spoofer"},
        {"mtaspoofer.exe", "MTA serial spoofer"},
        {"cleo.asi", "CLEO ASI - Script hook"},
        {"sampasireloader.exe", "SA-MP ASI reloader"},
        {"sampfuncs.exe", "SAMPFuncs - SA-MP cheat"},
        {"modmenu.exe", "Mod menu cheat"},
        {"mtamodmenu.exe", "MTA mod menu"},
        {"fivemmenu.exe", "FiveM menu cheat"},
        {"redm.exe", "RedM cheat"},
        {"ragehook.exe", "RageMP hook"},
        {"gasmaskagent.exe", "GasMask Agent - MTA Lua executor core"},
        {"sobfox.exe", "SobFoX - MTA aimbot cheat"},
        {"superspoofer.exe", "SuperSpoofer - MTA serial spoofer (ntkernelMC)"},
        {"nexida.exe", "Nexida Project - MTA Lua engine"},
        {"nexidaproject.exe", "Nexida Project - MTA Lua engine"},
        {"deadlyteam.exe", "Deadly Team - MTA AC bypass tool (cracked)"},
        {"deadly_team.exe", "Deadly Team - MTA AC bypass"},
        {"deadly team cracked.exe", "Deadly Team cracked - MTA AC bypass"},
        {"inferno.exe", "MTA Inferno - cheat suite"},
        {"multitheftautoinferno.exe", "Multi Theft Auto Inferno - cheat"},
        {"mtahook.exe", "MTA:SA Hook - memory hook cheat"},
        {"boxyhax.exe", "BoxyHaxSamp - multihack"},
        {"team fox.exe", "Team Fox - MTA internal cheat"},
        {"mta_airbreak.exe", "MTA airbreak cheat"},
        {"mta_teleport.exe", "MTA teleport cheat"},
        {"mta_godmode.exe", "MTA godmode cheat"},
        {"mta_speedhack.exe", "MTA speedhack cheat"},
        {"mta_noclip.exe", "MTA noclip cheat"},
        {"mta_wallhack.exe", "MTA wallhack cheat"},
        {"mta_hile.exe", "MTA cheat (Turkish)"},
        {"mta_hack.exe", "MTA hack"},
        {"mta_loader.exe", "MTA cheat loader"},
        {"mta_trainer.exe", "MTA trainer"},
        {"moraltrainer.exe", "MoralTrainer - MTA trainer"},
        {"shadowhack.exe", "ShadowHack - MTA cheat"},
        {"darknet.exe", "DarkNet - MTA cheat"},
        // NEW — internet research confirmed MTA cheat files
        {"fuu.dll", "Fuu - MTA cheat DLL (TioICO/mta-cheat)"},
        {"fuu.exe", "Fuu - MTA cheat loader"},
        {"projectmta.dll", "ProjectMTA - Open source MTA cheat DLL"},
        {"projectmta.exe", "ProjectMTA - MTA cheat"},
        {"provhack.exe", "ProvHack - MTA:Province cheat (aimbot, ESP, airbreak)"},
        // removed dup: fairplaykd.exe
        {"faskick.dll", "FasKick - MTA cheat DLL"},
        {"alexload.asi", "AlexLoad - MTA ASI loader cheat"},
        {"modloader.asi", "ModLoader ASI - Used for MTA mod loading"},
        {"rdry.rar", "RDRY - MTA cheat archive"},
        {"shx.dll", "SHX - MTA cheat DLL (command-line triggered)"},
        {"shx.exe", "SHX - MTA cheat loader"},
        {"sadrazam.exe", "Sadrazam - MTA cheat (ProjectMTA variant)"},
        {"sadrazam.dll", "Sadrazam - MTA cheat DLL"},
        {"provinceaimbot.exe", "Province Aimbot - MTA:Province cheat"},
        {"mta_patcher.exe", "MTA Patcher - Modifies MTA client for cheats"},
        {"mtapatcher.exe", "MTA Patcher - Modifies MTA client for cheats"},
        {"fairplaykiller.exe", "FairPlay Killer - Kills MTA FairPlay anti-cheat"},
        {"fpkiller.exe", "FP Killer - Kills MTA FairPlay"},
        {"ac_bypass.exe", "AC Bypass - MTA anti-cheat bypass tool"},
        {"mta_ac_bypass.exe", "MTA AC bypass tool"},
        {"mta_bypass.exe", "MTA bypass tool"},
        {"cheatloader.dll", "Cheat loader DLL (MTA)"},
        {"cheatmenu.dll", "Cheat menu DLL (MTA)"},
        {"hookmenu.dll", "Hook menu DLL (MTA)"},
        {"mta_reborn.exe", "MTA Reborn cheat"},
        {"mta_revolution.exe", "MTA Revolution cheat"},
        {"mta_pro.exe", "MTA Pro cheat"},
        {"mta_lite.exe", "MTA Lite cheat"},
        {"mta_vip.exe", "MTA VIP cheat"},
        {"mta_private.exe", "MTA Private cheat"},
        {"mta_inject.exe", "MTA injector"},
        {"mta_dll_inject.exe", "MTA DLL injector"},
        {"mta_zenith.exe", "MTA Zenith cheat"},
        {"mta_phantom.exe", "MTA Phantom cheat"},
        {"mta_apex.exe", "MTA Apex cheat"},
        {"mta_genesis.exe", "MTA Genesis cheat"},
    };

    // Tools that are suspicious but not definitive cheats (lower severity)
    public static readonly Dictionary<string, string> SuspiciousTools = new(StringComparer.OrdinalIgnoreCase)
    {
        {"ollydbg.exe", "OllyDbg - Debugger (may be used for cheat analysis)"},
        {"x64dbg.exe", "x64dbg - Debugger (may be used for cheat analysis)"},
        {"x32dbg.exe", "x32dbg - Debugger (may be used for cheat analysis)"},
        {"x96dbg.exe", "x96dbg - Debugger"},
        {"idaw.exe", "IDA Pro - Disassembler (may be used for cheat analysis)"},
        {"idaf.exe", "IDA Free"},
        {"idat.exe", "IDA Terminal"},
        {"ida64.exe", "IDA Pro 64-bit"},
        {"ida.exe", "IDA Pro"},
        // removed dup: dnspy.exe
        // removed dup: dnspyx86.exe
        // removed dup: ilspy.exe
        {"httpanalyzer.exe", "HTTP Analyzer"},
        {"fiddler.exe", "Fiddler - Web debugger"},
        {"charles.exe", "Charles Proxy"},
        {"burpsuite.exe", "Burp Suite - Security testing"},
        {"autoruns.exe", "Autoruns - Sysinternals startup manager"},
        {"autoruns64.exe", "Autoruns 64-bit"},
        {"procexp.exe", "Process Explorer - Sysinternals"},
        {"procexp64.exe", "Process Explorer 64-bit"},
        {"procmon.exe", "Process Monitor - Sysinternals"},
        {"procmon64.exe", "Process Monitor 64-bit"},
        {"vmmap.exe", "VMMap - Memory analysis tool"},
        {"rammap.exe", "RAMMap - Memory analysis tool"},
        {"tcpview.exe", "TCPView - Network connection viewer"},
        {"wireshark.exe", "Wireshark - Network analyzer"},
        {"tshark.exe", "TShark - Command-line Wireshark"},
        {"dumpcap.exe", "Dumpcap - Packet capture"},
        {"browserhistoryview.exe", "NirSoft BrowsingHistoryView - Browser forensic tool"},
        {"prefetchview.exe", "NirSoft PrefetchView"},
        {"winprefetchview.exe", "NirSoft WinPrefetchView"},
        {"usbdeview.exe", "NirSoft USBDeview"},
        {"produkey.exe", "NirSoft ProduKey"},
        {"sandboxie.exe", "Sandboxie - Sandbox tool (bypass technique)"},
        {"sandboxierpcss.exe", "Sandboxie RPC Service"},
        {"vmware.exe", "VMware Workstation"},
        {"vmware-vmx.exe", "VMware VM process"},
        {"virtualbox.exe", "Oracle VirtualBox"},
        {"vboxmanage.exe", "VirtualBox Manager"},
        {"qemu.exe", "QEMU Emulator"},
        {"qemu-system-x86_64.exe", "QEMU x86_64"},
        {"autohotkey.exe", "AutoHotkey - May be used for macro/automation"},
        {"autohotkey32.exe", "AutoHotkey 32-bit"},
        {"autohotkey64.exe", "AutoHotkey 64-bit"},
        {"autoit3.exe", "AutoIt v3 - May be used for compiled scripts"},
        {"autoit3_x64.exe", "AutoIt v3 64-bit"},
        {"aut2exe.exe", "AutoIt to EXE compiler"},
        {"tor.exe", "Tor Browser - anonymous browsing"},
        {"tor-browser.exe", "Tor Browser"},
        // removed dup: obs64.exe
        {"obs32.exe", "OBS Studio 32-bit"},
        {"obs.exe", "OBS Studio"},
        {"python.exe", "Python - May be used to run cheat scripts"},
        {"pythonw.exe", "Python (windowless)"},
        {"python3.exe", "Python 3"},
    };

    public static readonly Dictionary<string, string> CheatKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        {"mta hile", "MTA cheat search"},
        {"mta cheat", "MTA cheat search"},
        {"mta bedava hile", "MTA free cheat search"},
        {"mta free cheat", "MTA free cheat search"},
        {"mta aimbot", "MTA aimbot search"},
        {"mta esp", "MTA ESP search"},
        {"mta wallhack", "MTA wallhack search"},
        {"mta bypass", "MTA bypass search"},
        {"mta spoofer", "MTA spoofer search"},
        {"mta serial spoofer", "MTA serial spoofer search"},
        {"mta lua executor", "MTA Lua executor search"},
        {"mta lua injector", "MTA Lua injector search"},
        {"mta gasmask", "GasMask MTA cheat search"},
        {"gasmask mta", "GasMask MTA Lua executor"},
        {"gasmask lua executor", "GasMask Lua executor"},
        {"nexus mta", "Nexus MTA cheat search"},
        {"capyprivate mta", "CapyPrivate MTA cheat search"},
        {"0x mta", "0x MTA cheat search"},
        {"exterium mta", "Exterium MTA cheat search"},
        {"exterium menu", "Exterium MTA cheat menu"},
        {"shine mta", "Shine MTA menu search"},
        {"mtacheat", "MTA cheat general search"},
        {"mtahack", "MTA hack search"},
        {"mta mod menu", "MTA mod menu search"},
        {"mta godmode", "MTA godmode cheat"},
        {"mta airbreak", "MTA airbreak cheat"},
        {"mta teleport", "MTA teleport cheat"},
        {"mta invisible", "MTA invisible cheat"},
        {"mta speed hack", "MTA speed hack"},
        {"mta super jump", "MTA super jump"},
        {"mta no clip", "MTA no clip"},
        {"mta vehicle fly", "MTA vehicle fly cheat"},
        {"ugbase mta", "UGBase MTA forum search"},
        {"ugbase.eu", "UGBase.eu - Cheat forum"},
        {"unknowncheats mta", "UnknownCheats MTA forum"},
        {"unknowncheats", "UnknownCheats - Cheat forum"},
        {"uc mta", "UC MTA forum"},
        {"crazycapy mta", "CrazyCapy MTA cheat store"},
        {"crazycapy", "CrazyCapy - Cheat store"},
        {"cheatermad mta", "CheaterMad MTA forum"},
        {"cheatermad.com", "CheaterMad - Cheat site"},
        {"mta cheat download", "MTA cheat download search"},
        {"mta hile indir", "MTA cheat download (Turkish)"},
        {"mta hile yükle", "MTA cheat install (Turkish)"},
        {"mta cheat free download", "MTA free cheat download"},
        {"mta cheat 2025", "MTA current cheat search"},
        {"mta cheat 2024", "MTA cheat search"},
        {"mta hack download", "MTA hack download"},
        {"mta lua script hack", "MTA Lua script hack"},
        {"mta cheat menu", "MTA cheat menu search"},
        {"mta hack menu", "MTA hack menu search"},
        {"mtasa cheat", "MTA:SA cheat search"},
        {"mtasa hack", "MTA:SA hack search"},
        {"multitheftauto cheat", "Multi Theft Auto cheat search"},
        {"multitheftauto hack", "Multi Theft Auto hack search"},
        {"gta san andreas multiplayer cheat", "GTA SA MP cheat search"},
        {"fivem cheat", "FiveM cheat search"},
        {"fivem hack", "FiveM hack search"},
        {"fivem lua executor", "FiveM Lua executor"},
        {"redm cheat", "RedM cheat search"},
        {"rage mp hack", "RageMP hack"},
        {"altv cheat", "alt:V cheat"},
        {"keyauth", "KeyAuth - Authentication API commonly used by cheats"},
        {"keyauth.cc", "KeyAuth cheat authentication"},
        {"eauth", "eAuth - Authentication API"},
        {"eauth.us.to", "eAuth cheat authentication"},
        {"cheat loader", "Cheat loader search"},
        {"cheat injector", "Cheat injector search"},
        {"dll injector", "DLL injector search"},
        {"manual map", "Manual map injector search"},
        {"manual mapper", "Manual mapper"},
        {"spoofer", "Spoofer search"},
        {"hwid spoofer", "HWID spoofer search"},
        {"serial spoofer", "Serial spoofer"},
        {"mta serial", "MTA serial search"},
        {"bypass anticheat", "Anticheat bypass search"},
        {"bypass mta anticheat", "MTA anticheat bypass"},
        {"mta anticheat bypass", "MTA anticheat bypass search"},
        {"napse bypass", "Napse AC bypass search"},
        {"napse.ac", "Napse AC reference"},
        {"ocean bypass", "Ocean AC bypass search"},
        {"ocean.ac", "Ocean AC reference"},
        {"anticheat.ac", "Ocean AC anti-cheat"},
        {"detect.ac", "Detect AC reference"},
        {"detect bypass", "Detect AC bypass search"},
        {"echo ac bypass", "Echo AC bypass"},
        {"siles.ac", "Siles AC"},
        {"abbys ac", "Abyss AC bypass"},
        {"pc checker bypass", "PC checker bypass"},
        {"screenshare bypass", "Screenshare bypass search"},
        {"ss bypass", "SS bypass"},
        {"cleaner tool", "Cleaner tool (forensic cleaner)"},
        {"trace eraser", "Trace eraser"},
        {"privacy eraser", "Privacy eraser"},
        {"windows log cleaner", "Windows log cleaner"},
        {"event log cleaner", "Event log cleaner"},
        {"prefetch cleaner", "Prefetch cleaner"},
        {"prefetch delete", "Prefetch deletion tool"},
        {"usn journal cleaner", "USN journal cleaner"},
        {"journal delete", "Journal deletion tool"},
        {"bam cleaner", "BAM cleaner"},
        {"timestomp", "Timestomp - Timestamp manipulation"},
        {"timestomping", "Timestomping tool"},
        {"vmprotect", "VMProtect - Cheat protection"},
        {"themida", "Themida - Cheat protection"},
        {"execute pe from memory", "Execute PE from memory"},
        {"reflection injection", "Reflection DLL injection"},
        {"process hollowing", "Process hollowing"},
        {"runpe", "RunPE - PE injector"},
        {"fileless malware", "Fileless execution"},
        {"fileless cheat", "Fileless cheat"},
        {"dma cheat", "DMA cheat search"},
        {"dma card", "DMA card (hardware cheat)"},
        {"dma fuser", "DMA fuser device"},
        {"pcileech", "PCILeech - DMA attack tool"},
        {"dma attack", "DMA attack tool"},
        {"kernel cheat", "Kernel-level cheat"},
        {"kernel driver cheat", "Kernel driver cheat"},
        {"kernel mode cheat", "Kernel mode cheat"},
        {"byovd", "Bring Your Own Vulnerable Driver"},
        {"vulnerable driver", "Vulnerable driver"},
        {"driver cheat", "Driver-based cheat"},
        {"mapper driver", "Kernel driver mapper"},
        {"kdmapper", "Kernel driver mapper tool"},
        {"gdrv", "GDRV vulnerable driver"},
        {"ezmapper", "Ease mapper kernel driver"},
        {"unsigned driver", "Unsigned driver load"},
        {"test signing", "Test signing mode enable"},
        {"testsigning", "Test signing mode"},
        {"bcdedit testsigning", "Test signing BCDEdit"},
        {"hypervisor cheat", "Hypervisor-based cheat"},
        {"vmxrootkit", "VMX rootkit"},
        {"simple bypass", "Simple bypass tool"},
        {"cheat engine bypass", "Cheat Engine bypass"},
        {"anticheat analyzer", "Anticheat analysis tool"},
        {"dumper", "Memory dumper tool"},
        {"game dumper", "Game memory dumper"},
        {"lua executor", "Lua executor"},
        {"lua injector", "Lua injector"},
        {"lua bypass", "Lua bypass"},
        {"moonloader", "MoonLoader - Lua hook"},
        {"cleo", "CLEO mod - Script hook"},
        {"vape", "Vape cheat client"},
        {"vape lite", "Vape Lite cheat"},
        {"vape v4", "Vape V4 cheat"},
        {"liquidbounce", "LiquidBounce cheat client"},
        {"meteor client", "Meteor cheat client"},
        {"sigma client", "Sigma cheat client"},
        {"aristois", "Aristois cheat client"},
        {"inertia client", "Inertia cheat client"},
        {"wurst client", "Wurst cheat client"},
        {"lambda client", "Lambda cheat client"},
        {"novoline", "Novoline cheat"},
        {"rise client", "Rise cheat client"},
    };

    public static readonly string[] CheatFilePatterns = new[]
    {
        "*cheat*", "*hack*", "*hile*", "*crack*", "*loader*",
        "*injector*", "*dumper*", "*spoofer*", "*bypass*",
        "*executor*", "*trainer*", "*mod menu*", "*exploit*",
        "*cracked*", "*keygen*", "*crackme*"
    };

    // Injected / cheat modules (DLL/ASI) loaded into processes - used by LoadedModulesScanner
    public static readonly Dictionary<string, string> CheatModules = new(StringComparer.OrdinalIgnoreCase)
    {
        {"franny.dll", "Franny cheat DLL"},
        {"hydrogen.dll", "Hydrogen cheat DLL"},
        {"hydrogenmenu.dll", "Hydrogen menu DLL"},
        {"hydrogenhook.dll", "Hydrogen hook DLL"},
        {"menu.dll", "Cheat menu DLL"},
        {"cheat.dll", "Cheat DLL"},
        {"inject.dll", "Injected cheat DLL"},
        {"hook.dll", "Hook DLL (cheat injection)"},
        {"hookloader.dll", "Hook loader DLL"},
        {"d3d9hook.dll", "D3D9 hook DLL"},
        {"dx9hook.dll", "DirectX9 hook DLL"},
        {"d3d9.dll", "Custom D3D9.dll (cheat overlay/wallhack)"},
        {"dinput8.dll", "Custom dinput8.dll (input hook)"},
        {"dxgi.dll", "Custom dxgi.dll"},
        {"menu.asi", "Cheat menu ASI"},
        // removed dup: cleo.asi
        {"moonloader.asi", "MoonLoader ASI - Lua hook"},
        // removed dup: modloader.asi
        // removed dup: alexload.asi
        {"s0beit.asi", "s0beit ASI trainer"},
        {"s0beit.dll", "s0beit trainer DLL"},
        {"multihack.asi", "Multihack ASI"},
        {"multihack.dll", "Multihack DLL"},
        {"gtahook.asi", "GTA hook ASI"},
        {"mphook.dll", "Multiplayer hook DLL"},
        {"speedi.asi", "Speedi ASI"},
        {"franny.asi", "Franny ASI"},
        {"gta_sa.exe", "Custom gta_sa.exe (cheat client)"},
        {"samp.dll", "Custom SA-MP DLL"},
        {"samp.asi", "Custom SA-MP ASI"},
        {"eclipso.dll", "Eclipso cheat DLL"},
        {"phantom.dll", "Phantom cheat DLL"},
        {"scriptware.dll", "Scriptware DLL"},
        {"extmenu.dll", "External menu cheat DLL"},
        {"aimbot.dll", "Aimbot DLL"},
        {"esp.dll", "ESP/wallhack DLL"},
        {"wallhack.dll", "Wallhack DLL"},
        {"norecoil.dll", "No-recoil macro DLL"},
        {"macro.dll", "Macro DLL"},
        {"bypass.dll", "Bypass DLL"},
        {"spoofer.dll", "HWID/serial spoofer DLL"},
        {"client.dll", "Cheat client DLL"},
        {"cheatengine-x86_64.exe.dll", "Cheat Engine injected"},
        {"nativecheat.dll", "Native cheat DLL"},
        {"hydra.dll", "Hydra cheat DLL"},
        {"phantomcheat.dll", "Phantom cheat DLL"},
        {"neutrino.dll", "Neutrino injector DLL"},
        {"exelans.dll", "Exelans plugin DLL"},
        {"shine.dll", "Shine menu DLL"},
        {"nexus.dll", "Nexus cheat DLL"},
        {"capyprivate.dll", "CapyPrivate cheat DLL"},
        {"exterium.dll", "Exterium menu DLL"},
        {"0xcheat.dll", "0x cheat DLL"},
        {"gasmask.dll", "GasMask Lua executor DLL"},
        {"sapphire.dll", "Sapphire cheat DLL"},
        {"yubinject.dll", "YuB injector DLL"},
        {"gasmaskagent.dll", "GasMask Agent DLL - MTA Lua executor core (confirmed)"},
        // removed dup: fuu.dll
        // removed dup: projectmta.dll
        // removed dup: faskick.dll
        // removed dup: shx.dll
        // removed dup: sadrazam.dll
        // removed dup: cheatloader.dll
        // removed dup: cheatmenu.dll
        // removed dup: hookmenu.dll
        {"mta_air.dll", "MTA airbreak DLL"},
        {"mta_aim.dll", "MTA aimbot DLL"},
        {"mta_esp.dll", "MTA ESP DLL"},
        {"mta_wall.dll", "MTA wallhack DLL"},
        {"mta_god.dll", "MTA godmode DLL"},
        {"mta_speed.dll", "MTA speedhack DLL"},
        {"rdrte.dll", "RDRTE - MTA cheat DLL"},
        // NEW — user-provided + YouTube research
        {"footballacademyloader.exe", "FootballAcademyLoader - MTA cheat loader"},
        {"voidz.dll", "Voidz - MTA cheat DLL"},
        {"overwackloader.exe", "OverwackLoader - MTA cheat loader"},
        {"overwack.dll", "Overwack - MTA cheat DLL"},
        {"overwack.exe", "Overwack - MTA cheat client"},
        {"footballacademy.dll", "FootballAcademy - MTA cheat DLL"},
        {"footballacademy.exe", "FootballAcademy - MTA cheat client"},
        {"voidz.exe", "Voidz - MTA cheat client"},
        {"deadlyteam.dll", "Deadly Team - MTA AC bypass DLL"},
        {"inferno.dll", "MTA Inferno - cheat DLL"},
        {"mtahook.dll", "MTA:SA Hook - memory hook DLL"},
        {"boxyhax.dll", "BoxyHaxSamp - multihack DLL"},
        {"shinehook.dll", "Shine hook DLL"},
        {"sobfox.dll", "SobFoX - MTA aimbot DLL"},
        // removed dup: hydrogenmenu.dll
        // removed dup: hydrogenhook.dll
        {"mta_airbreak.dll", "MTA airbreak DLL"},
        {"mta_noclip.dll", "MTA noclip DLL"},
        {"mta_teleport.dll", "MTA teleport DLL"},
        {"mta_superjump.dll", "MTA super jump DLL"},
        {"mta_vehiclefly.dll", "MTA vehicle fly DLL"},
        {"mta_invisible.dll", "MTA invisible DLL"},
        {"mta_reborn.dll", "MTA Reborn cheat DLL"},
        {"mta_revolution.dll", "MTA Revolution cheat DLL"},
        {"mta_pro.dll", "MTA Pro cheat DLL"},
        {"mta_vip.dll", "MTA VIP cheat DLL"},
        {"mta_apex.dll", "MTA Apex cheat DLL"},
        {"mta_zenith.dll", "MTA Zenith cheat DLL"},
        {"mta_genesis.dll", "MTA Genesis cheat DLL"},
        {"mta_phantom.dll", "MTA Phantom cheat DLL"},
        {"loader.dll", "Cheat loader DLL (MTA context)"},
        {"loader.asi", "ASI loader (MTA cheat context)"},
        {"modmenu.asi", "Mod menu ASI (MTA context)"},
        {"mta_reaper.dll", "MTA Reaper cheat DLL"},
        {"mta_titan.dll", "MTA Titan cheat DLL"},
        {"mta_storm.dll", "MTA Storm cheat DLL"},
        {"mta_chaos.dll", "MTA Chaos cheat DLL"},
        {"gtagaming.dll", "GTA gaming cheat DLL"},
        {"mta_patch.dll", "MTA patch DLL"},
        {"netc_patcher.dll", "NetC patcher - Patches MTA networking"},
        {"client_patcher.dll", "Client patcher - Patches MTA client"},
        {"fairplay_bypass.dll", "FairPlay bypass DLL"},
        {"ac_bypass.dll", "AC bypass DLL"},
        {"mta_ac_bypass.dll", "MTA AC bypass DLL"},
    };

    public static readonly string[] SuspiciousExtensions = new[]
    {
        ".exe", ".dll", ".sys", ".bin", ".scr", ".ps1",
        ".vbs", ".bat", ".cmd", ".js", ".jse", ".vbe",
        ".wsf", ".wsh", ".msi", ".msp", ".com", ".pif",
        ".cpl", ".gadget", ".asp", ".aspx", ".php"
    };

    public static readonly string[] VPNProcessNames = new[]
    {
        "vpnui", "openvpn", "nordvpn", "protonvpn", "expressvpn",
        "wireguard", "windscribe", "cyberghost", "surfshark",
        "privateinternetaccess", "pia", "tunnelbear", "vyprvpn",
        "hotspotshield", "ipvanish", "purevpn", "zenmate",
        "hideman", "proxifier", "proxycap", "psiphon", "ultrasurf"
    };

    public static readonly string[] VPNAdapterKeywords = new[]
    {
        "tap", "tun", "vpn", "openvpn", "wireguard", "nordlynx",
        "proton", "pia", "windscribe", "surfshark"
    };

    public static readonly string[] SuspiciousServicesNames = new[]
    {
        "sandboxie", "vmtool", "vbox", "vmsrvc", "vmware",
    };

    // Legitimate Windows / app files that must NEVER be flagged by pattern matching.
    // These match suspicious patterns (loader, cheat, hack, dumper etc.) but are safe.
    public static readonly HashSet<string> LegitimateFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        // Windows API-set DLLs (api-ms-win-core-*-*)
        // handled by prefix check in IsLegitimateFile, but list a few common ones
        "api-ms-win-core-libraryloader-l1-1-0.dll",
        "api-ms-win-core-libraryloader-l1-2-0.dll",
        // Microsoft WebView2
        "webview2loader.dll",
        "webview2loaderEx.dll",
        // .NET runtime loaders
        "system.runtime.loader.dll",
        "assemblyloader.dll",
        "microsoft.visualstudio.web.pageinspector.loader.dll",
        "coloader80.dll",
        "clrcompression.dll",
        // NVIDIA / PhysX
        "physxloader.dll",
        "physxloader64.dll",
        "physxupdateloader.dll",
        "physxupdateloader64.dll",
        "nvcuda.dll",
        "nvoglv32.dll",
        "nvoglv64.dll",
        "nvencodeapi.dll",
        "nvencodeapi64.dll",
        // Anti-cheat (NOT cheats!)
        "easyanticheat.exe",
        "easyanticheat_eos.exe",
        "easyanticheat.sys",
        "eaanticheat.installer.exe",
        "eaanticheat.gameservice.exe",
        "eaanticheat.gameservice.dll",
        "battleye.dll",
        "battleye_launcher.exe",
        "beservice.exe",
        "beservice_x64.exe",
        "eac_launcher.exe",
        "fairplaykd.exe",
        "fairplaykd.sys",
        // Game platform / store loaders (legitimate)
        "steam.exe",
        "steamwebhelper.exe",
        "steamerrorreport.exe",
        "gamebar.exe",
        "gamebarpers.exe",
        "gamehud.exe",
        "gamingservices.exe",
        "gamingoverlay.exe",
        "gamingconfig.exe",
        // Sysinternals / dev tools that aren't cheats
        "autoruns.exe",
        "autoruns64.exe",
        "procexp.exe",
        "procexp64.exe",
        "procmon.exe",
        "procmon64.exe",
        "vmmap.exe",
        "rammap.exe",
        "tcpview.exe",
        "dumpcap.exe",
        "tshark.exe",
        "wireshark.exe",
        "ida.exe",
        "ida64.exe",
        "idat.exe",
        "idaf.exe",
        "x96dbg.exe",
        "x64dbg.exe",
        "x32dbg.exe",
        "dnspy.exe",
        "dnspyx86.exe",
        "ilspy.exe",
        "dotnet.exe",
        "msixbackgroundtasksexecutor.exe",
        // Common apps with "loader" in name
        "assetreuploader.exe",
        "loguploader.exe",
        "log-uploader.exe",
        "crashuploader.exe",
        "steamworkshopuploader.exe",
        "pakloader.exe",
        "melonloader.installer.exe",
        "qq_minigame_loader.dll",
        "ttnetdownloadercrossplatform.dll",
        "downloader.dll",
        "uploader.dll",
        "preloader_s.dll",
        "bifrost_loader.2.dll",
        "sprudo_loader_1770068902.exe",
        "loaderbankroll.exe",
        "valoader.exe",
        "kernelmoduleunloader.exe",
        "upc_r2_loader64.dll",
        "citizen-level-loader-five.dll",
        "citizen-mod-loader-five.dll",
        "handling-loader-five.dll",
        "coloader80.dll",
        // Windows system DLLs that get loaded by everything
        "dxgi.dll",
        "d3d9.dll",
        "d3d10.dll",
        "d3d11.dll",
        "d3d12.dll",
        "dinput8.dll",
        "dinput.dll",
        "dsound.dll",
        "ddraw.dll",
        "d3dcompiler_43.dll",
        "d3dcompiler_47.dll",
        "d3dcompiler_50.dll",
        "opengl32.dll",
        "glu32.dll",
        "msacm32.dll",
        "winmm.dll",
        "imm32.dll",
        "oleaut32.dll",
        "wininet.dll",
        "winhttp.dll",
        "urlmon.dll",
        "mshtml.dll",
        "jscript.dll",
        "vbscript.dll",
        "scrrun.dll",
        "msxml3.dll",
        "msxml6.dll",
        "xmllite.dll",
        "iertutil.dll",
        "iertutil.dll",
        "iertutil.dll",
        // Misc legitimate
        "python.exe",
        "python3.exe",
        "pythonw.exe",
        "python312.dll",
        "python311.dll",
        "python310.dll",
        "python39.dll",
        "vmp.exe",
        "themida.exe",
        "winlicense.exe",
        "resourcehacker.exe",
        "ssh-keygen.exe",
        "minidumper.exe",
        "sqldumper.exe",
        "cudagpuinfodumper.exe",
        "dotnet.exe",
        "breakpadinjector.dll",
        "zed_explorer_command_injector.dll",
        "system.runtime.loader.dll",
        "api-ms-win-core-libraryloader-l1-1-0.dll",
        "api-ms-win-core-libraryloader-l1-2-0.dll",
        "simplensent.dll",
        "simpleinjectedclasslibrary.dll",
        "simpletestinjector.dll",
        "cheatengine76.exe",
        "cheat engine.exe",
    };

    // Process names where injected modules ARE suspicious (games that get cheated)
    public static readonly HashSet<string> GameProcesses = new(StringComparer.OrdinalIgnoreCase)
    {
        "multi theft auto.exe", "mta.exe", "gta_sa.exe", "gtavc.exe", "gta3.exe",
        "gta4.exe", "gta5.exe", "gtav.exe", "gta_san_andreas.exe",
        "samp.exe", "samp_debug.exe",
        "fivem.exe", "fivembrowsersvc.exe", "citizenfx.exe",
        "rage_mp.exe", "ragemp.exe", "altv.exe",
        "minecraft.exe", "javaw.exe",
        "cs2.exe", "csgo.exe", "csgo_launcher.exe",
        "valorant.exe", "valorant-win64-shipping.exe",
        "r6game.exe", "rainbowsix.exe", "r6.exe",
        "apex_legends.exe", "r5apex.exe", "apex.exe",
        "fortnite.exe", "fortniteclient-win64-shipping.exe",
        "pubg.exe", "tslgame.exe",
        "eoft.exe", "eft.exe", "escapefromtarkov.exe",
        "dayz.exe", "h1z1.exe",
        "dota2.exe", "csgo.exe",
        "hl2.exe", "csgo.exe",
    };

    /// <summary>
    /// Checks if a file name is a known legitimate Windows/app file that should never be flagged.
    /// Also handles api-ms-win-* and ext-ms-* API set prefix matching.
    /// </summary>
    public static bool IsLegitimateFile(string fileName)
    {
        if (string.IsNullOrEmpty(fileName)) return true;
        var lower = fileName.ToLower().Trim();

        if (LegitimateFiles.Contains(lower)) return true;

        // Windows API set DLLs: api-ms-win-*, ext-ms-*, api-ms-*
        if (lower.StartsWith("api-ms-win-") || lower.StartsWith("ext-ms-") || lower.StartsWith("api-ms-"))
            return true;

        // .NET runtime assemblies
        if (lower.StartsWith("system.runtime") || lower.StartsWith("microsoft."))
            return true;

        // NVIDIA / GPU driver DLLs
        if (lower.StartsWith("nv") && (lower.EndsWith(".dll") || lower.EndsWith(".exe")))
            return true;

        return false;
    }

    /// <summary>
    /// Checks if a file is an anti-cheat tool (EasyAntiCheat, BattlEye, etc.) — these contain "cheat" in the name but are legitimate.
    /// </summary>
    public static bool IsAntiCheatTool(string fileName)
    {
        var lower = (fileName ?? "").ToLower();
        return lower.Contains("easyanticheat") ||
               lower.Contains("battleye") ||
               lower.Contains("beservice") ||
               lower.Contains("eac_launcher") ||
               lower.Contains("fairplay") ||
               lower.Contains("eaanticheat") ||
               lower.Contains("eac_launcher") ||
               lower.Contains("anticheat");
    }

    /// <summary>
    /// Checks if a file/process name is specifically an MTA (Multi Theft Auto) cheat.
    /// Matches: known MTA brand names, "mta"+cheat-word combos, MTA-specific tools.
    /// Does NOT match: generic loaders/injectors that aren't MTA-specific.
    /// </summary>
    public static bool IsMtaCheat(string fileName, string? source = null, string? reason = null)
    {
        var lower = (fileName ?? "").ToLower().Trim();
        if (string.IsNullOrEmpty(lower)) return false;

        // 1. If loaded into MTA/GTA process, ANY suspicious module is MTA-related
        var src = (source ?? "").ToLower();
        if (src.Contains("loaded module (multi theft auto") ||
            src.Contains("loaded module (mta") ||
            src.Contains("loaded module (gta_sa") ||
            src.Contains("loaded module (samp"))
            return true;

        // 2. Known MTA cheat brand names (exact or substring)
        var mtaBrands = new[]
        {
            "gasmask", "gasmaskagent", "sobfox", "nexida", "deadlyteam", "deadly team",
            "exterium", "capyprivate", "shine", "hydrogen", "hydrogenmenu",
            "franny", "speedi", "inferno", "boxyhax", "mtahook",
            "mtasacheats", "s0beit", "neutrino", "exelans", "eclipso",
            "nexus_mta", "simpleinjectormta", "samodinjector",
            "0xcheat", "scriptware", "superspoofer", "team fox",
        };
        foreach (var brand in mtaBrands)
        {
            if (lower.Contains(brand)) return true;
        }

        // 3. "mta" + cheat-word combination
        if (lower.Contains("mta") || lower.Contains("mtasa") || lower.Contains("multitheftauto"))
        {
            var cheatWords = new[] { "spoofer", "cheat", "hack", "hile", "inject",
                "executor", "aimbot", "esp", "wallhack", "menu", "mod", "bypass", "loader" };
            foreach (var word in cheatWords)
            {
                if (lower.Contains(word)) return true;
            }
        }

        // 4. MTA-specific file patterns
        if (lower.StartsWith("mta_") || lower.StartsWith("mta-"))
            return true;

        return false;
    }

    /// <summary>
    /// Checks if a file name contains a known cheat brand name (for disk scanning).
    /// This catches files like "GasMask_Lua_Executor_v0.4.7.exe" that don't match exact names.
    /// </summary>
    public static bool ContainsCheatBrand(string fileName)
    {
        var lower = (fileName ?? "").ToLower().Trim();
        if (string.IsNullOrEmpty(lower)) return false;

        if (IsLegitimateFile(lower) || IsAntiCheatTool(lower)) return false;

        var brands = new[]
        {
            "gasmask", "sobfox", "nexida", "deadlyteam", "deadly team",
            "exterium", "capyprivate", "hydrogen", "hydrogenmenu",
            "franny", "speedi", "inferno", "boxyhax", "mtahook",
            "s0beit", "neutrino", "exelans", "eclipso", "phantomcheat",
            "nexus", "scriptware", "superspoofer", "crespo", "wiizard",
            "cheatengine", "artmoney", "wemod", "fling",
            "vape", "liquidbounce", "meteor", "sigma", "aristois", "wurst",
            "novoline", "rise client", "memprocfs", "pcileech",
            "kdmapper", "xenos", "ezmapper", "scyllahide",
            "extreme injector", "simple injector", "processhacker",
        };
        foreach (var brand in brands)
        {
            if (lower.Contains(brand)) return true;
        }
        return false;
    }

    public static bool IsSystemProcess(string processName)
    {
        var lower = processName.ToLower().Trim();
        if (string.IsNullOrEmpty(lower)) return true;
        return SystemProcessWhitelist.Contains(lower);
    }
}
